// Broadband source definitions for the first online access checks.
//
// These are candidate public web pages to check politely. They are not yet a
// pricing feed, scraper configuration, or endorsement of any source.

const broadbandSources = [
  {
    sourceId: 'bt',
    name: 'BT',
    sourceType: 'provider-direct',
    baseUrl: 'https://www.bt.com',
    candidateBroadbandUrl: 'https://www.bt.com/broadband',
    notes: 'Provider direct broadband landing page candidate.',
    enabled: true,
  },
  {
    sourceId: 'sky',
    name: 'Sky',
    sourceType: 'provider-direct',
    baseUrl: 'https://www.sky.com',
    candidateBroadbandUrl: 'https://www.sky.com/broadband',
    notes: 'Provider direct broadband landing page candidate.',
    enabled: true,
  },
  {
    sourceId: 'virgin-media',
    name: 'Virgin Media',
    sourceType: 'provider-direct',
    baseUrl: 'https://www.virginmedia.com',
    candidateBroadbandUrl: 'https://www.virginmedia.com/broadband',
    notes: 'Provider direct broadband landing page candidate.',
    enabled: true,
  },
  {
    sourceId: 'vodafone',
    name: 'Vodafone',
    sourceType: 'provider-direct',
    baseUrl: 'https://www.vodafone.co.uk',
    candidateBroadbandUrl: 'https://www.vodafone.co.uk/broadband',
    notes: 'Provider direct broadband landing page candidate.',
    enabled: true,
  },
  {
    sourceId: 'talktalk',
    name: 'TalkTalk',
    sourceType: 'provider-direct',
    baseUrl: 'https://www.talktalk.co.uk',
    candidateBroadbandUrl: 'https://www.talktalk.co.uk/broadband',
    notes: 'Provider direct broadband landing page candidate.',
    enabled: true,
  },
  {
    sourceId: 'plusnet',
    name: 'Plusnet',
    sourceType: 'provider-direct',
    baseUrl: 'https://www.plus.net',
    candidateBroadbandUrl: 'https://www.plus.net/broadband/',
    notes: 'Provider direct broadband landing page candidate.',
    enabled: true,
  },
  {
    sourceId: 'ee',
    name: 'EE',
    sourceType: 'provider-direct',
    baseUrl: 'https://ee.co.uk',
    candidateBroadbandUrl: 'https://ee.co.uk/broadband',
    notes: 'Provider direct broadband landing page candidate.',
    enabled: true,
  },
  {
    sourceId: 'hyperoptic',
    name: 'Hyperoptic',
    sourceType: 'provider-direct',
    baseUrl: 'https://www.hyperoptic.com',
    candidateBroadbandUrl: 'https://www.hyperoptic.com/broadband/',
    notes: 'Provider direct broadband landing page candidate.',
    enabled: true,
  },
  {
    sourceId: 'community-fibre',
    name: 'Community Fibre',
    sourceType: 'provider-direct',
    baseUrl: 'https://communityfibre.co.uk',
    candidateBroadbandUrl: 'https://communityfibre.co.uk/',
    notes: 'Provider direct broadband landing page candidate.',
    enabled: true,
  },
  {
    sourceId: 'uswitch',
    name: 'Uswitch',
    sourceType: 'comparison-site',
    baseUrl: 'https://www.uswitch.com',
    candidateBroadbandUrl: 'https://www.uswitch.com/broadband/',
    notes: 'Comparison site broadband landing page candidate.',
    enabled: true,
  },
  {
    sourceId: 'moneysupermarket',
    name: 'MoneySuperMarket',
    sourceType: 'comparison-site',
    baseUrl: 'https://www.moneysupermarket.com',
    candidateBroadbandUrl: 'https://www.moneysupermarket.com/broadband/',
    notes: 'Comparison site broadband landing page candidate.',
    enabled: true,
  },
  {
    sourceId: 'compare-the-market',
    name: 'Compare the Market',
    sourceType: 'comparison-site',
    baseUrl: 'https://www.comparethemarket.com',
    candidateBroadbandUrl: 'https://www.comparethemarket.com/broadband/',
    notes: 'Comparison site broadband landing page candidate.',
    enabled: true,
  },
  {
    sourceId: 'broadband-genie',
    name: 'Broadband Genie',
    sourceType: 'comparison-site',
    baseUrl: 'https://www.broadbandgenie.co.uk',
    candidateBroadbandUrl: 'https://www.broadbandgenie.co.uk/broadband',
    notes: 'Comparison site broadband landing page candidate.',
    enabled: true,
  },
  {
    sourceId: 'confused',
    name: 'Confused.com',
    sourceType: 'comparison-site',
    baseUrl: 'https://www.confused.com',
    candidateBroadbandUrl: 'https://www.confused.com/broadband',
    notes: 'Comparison site broadband landing page candidate.',
    enabled: true,
  },
];

module.exports = broadbandSources;
