/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited manually.
// It is generated by Next.js and committed here so TypeScript can understand Next.js types.
