// Fake sample broadband deals used by the terminal comparison script.
//
// These are NOT live prices and should not be used to buy broadband.
// They are simple example records so beginners can see what the pricing
// calculator expects and how comparison tables can be generated.

const sampleDeals = [
  {
    dealId: 'OX-BT-36',
    postcodeArea: 'OX',
    provider: 'BT',
    packageName: 'Fibre Essential Sample',
    source: 'Provider Direct',
    speedMbps: 36,
    speedTier: '35-75 Mbps',
    advertisedMonthlyPrice: 27.99,
    contractLengthMonths: 24,
    annualAprilPriceRise: 3,
    setupFee: 0,
    installationFee: 0,
    deliveryFee: 4.99,
    routerFee: 0,
    activationFee: 0,
    voucherValue: 0,
    rewardCardValue: 60,
    cashbackValue: 0,
    billCreditValue: 0,
    freeMonthsDiscountValue: 0,
    otherUpfrontCosts: 0,
    otherDiscounts: 0,
    lastCheckedDate: '2026-06-01',
  },
  {
    dealId: 'OX-SKY-61',
    postcodeArea: 'OX',
    provider: 'Sky',
    packageName: 'Superfast Sample',
    source: 'Comparison Site Sample',
    speedMbps: 61,
    speedTier: '35-75 Mbps',
    advertisedMonthlyPrice: 26,
    contractLengthMonths: 24,
    annualAprilPriceRise: 3,
    setupFee: 5,
    installationFee: 0,
    deliveryFee: 0,
    routerFee: 0,
    activationFee: 0,
    voucherValue: 40,
    rewardCardValue: 0,
    cashbackValue: 0,
    billCreditValue: 0,
    freeMonthsDiscountValue: 0,
    otherUpfrontCosts: 0,
    otherDiscounts: 0,
    lastCheckedDate: '2026-06-01',
  },
  {
    dealId: 'OX-VODAFONE-150',
    postcodeArea: 'OX',
    provider: 'Vodafone',
    packageName: 'Full Fibre 150 Sample',
    source: 'Voucher Sample',
    speedMbps: 150,
    speedTier: '100-300 Mbps',
    advertisedMonthlyPrice: 29,
    contractLengthMonths: 24,
    annualAprilPriceRise: 3,
    setupFee: 0,
    installationFee: 0,
    deliveryFee: 0,
    routerFee: 0,
    activationFee: 0,
    voucherValue: 75,
    rewardCardValue: 0,
    cashbackValue: 25,
    billCreditValue: 0,
    freeMonthsDiscountValue: 0,
    otherUpfrontCosts: 0,
    otherDiscounts: 0,
    lastCheckedDate: '2026-06-01',
  },
  {
    dealId: 'OX-TALKTALK-500',
    postcodeArea: 'OX',
    provider: 'TalkTalk',
    packageName: 'Full Fibre 500 Sample',
    source: 'Provider Direct',
    speedMbps: 500,
    speedTier: '500-900 Mbps',
    advertisedMonthlyPrice: 35,
    contractLengthMonths: 18,
    annualAprilPriceRise: 3,
    setupFee: 0,
    installationFee: 0,
    deliveryFee: 0,
    routerFee: 0,
    activationFee: 0,
    voucherValue: 0,
    rewardCardValue: 0,
    cashbackValue: 50,
    billCreditValue: 0,
    freeMonthsDiscountValue: 0,
    otherUpfrontCosts: 0,
    otherDiscounts: 0,
    lastCheckedDate: '2026-06-01',
  },
  {
    dealId: 'M-VIRGIN-132',
    postcodeArea: 'M',
    provider: 'Virgin Media',
    packageName: 'M125 Sample',
    source: 'Provider Direct',
    speedMbps: 132,
    speedTier: '100-300 Mbps',
    advertisedMonthlyPrice: 28.99,
    contractLengthMonths: 18,
    annualAprilPriceRise: 3.5,
    setupFee: 0,
    installationFee: 0,
    deliveryFee: 0,
    routerFee: 0,
    activationFee: 35,
    voucherValue: 0,
    rewardCardValue: 0,
    cashbackValue: 60,
    billCreditValue: 0,
    freeMonthsDiscountValue: 0,
    otherUpfrontCosts: 0,
    otherDiscounts: 0,
    lastCheckedDate: '2026-06-01',
  },
  {
    dealId: 'M-BT-500',
    postcodeArea: 'M',
    provider: 'BT',
    packageName: 'Full Fibre 500 Sample',
    source: 'Voucher Sample',
    speedMbps: 500,
    speedTier: '500-900 Mbps',
    advertisedMonthlyPrice: 39.99,
    contractLengthMonths: 24,
    annualAprilPriceRise: 3,
    setupFee: 0,
    installationFee: 0,
    deliveryFee: 4.99,
    routerFee: 0,
    activationFee: 0,
    voucherValue: 100,
    rewardCardValue: 0,
    cashbackValue: 0,
    billCreditValue: 0,
    freeMonthsDiscountValue: 0,
    otherUpfrontCosts: 0,
    otherDiscounts: 0,
    lastCheckedDate: '2026-06-01',
  },
  {
    dealId: 'M-SKY-900',
    postcodeArea: 'M',
    provider: 'Sky',
    packageName: 'Gigafast Sample',
    source: 'Comparison Site Sample',
    speedMbps: 900,
    speedTier: '900 Mbps+',
    advertisedMonthlyPrice: 44,
    contractLengthMonths: 24,
    annualAprilPriceRise: 3,
    setupFee: 0,
    installationFee: 0,
    deliveryFee: 0,
    routerFee: 0,
    activationFee: 0,
    voucherValue: 120,
    rewardCardValue: 0,
    cashbackValue: 0,
    billCreditValue: 0,
    freeMonthsDiscountValue: 0,
    otherUpfrontCosts: 0,
    otherDiscounts: 0,
    lastCheckedDate: '2026-06-01',
  },
  {
    dealId: 'M-TALKTALK-67',
    postcodeArea: 'M',
    provider: 'TalkTalk',
    packageName: 'Fibre 65 Sample',
    source: 'Provider Direct',
    speedMbps: 67,
    speedTier: '35-75 Mbps',
    advertisedMonthlyPrice: 25,
    contractLengthMonths: 18,
    annualAprilPriceRise: 3,
    setupFee: 0,
    installationFee: 0,
    deliveryFee: 0,
    routerFee: 0,
    activationFee: 0,
    voucherValue: 0,
    rewardCardValue: 0,
    cashbackValue: 35,
    billCreditValue: 0,
    freeMonthsDiscountValue: 0,
    otherUpfrontCosts: 0,
    otherDiscounts: 0,
    lastCheckedDate: '2026-06-01',
  },
  {
    dealId: 'SW-VODAFONE-910',
    postcodeArea: 'SW',
    provider: 'Vodafone',
    packageName: 'Full Fibre 910 Sample',
    source: 'Provider Direct',
    speedMbps: 910,
    speedTier: '900 Mbps+',
    advertisedMonthlyPrice: 42,
    contractLengthMonths: 24,
    annualAprilPriceRise: 3,
    setupFee: 0,
    installationFee: 0,
    deliveryFee: 0,
    routerFee: 0,
    activationFee: 0,
    voucherValue: 0,
    rewardCardValue: 100,
    cashbackValue: 0,
    billCreditValue: 0,
    freeMonthsDiscountValue: 0,
    otherUpfrontCosts: 0,
    otherDiscounts: 0,
    lastCheckedDate: '2026-06-01',
  },
  {
    dealId: 'SW-VIRGIN-1130',
    postcodeArea: 'SW',
    provider: 'Virgin Media',
    packageName: 'Gig1 Sample',
    source: 'Voucher Sample',
    speedMbps: 1130,
    speedTier: '900 Mbps+',
    advertisedMonthlyPrice: 45,
    contractLengthMonths: 18,
    annualAprilPriceRise: 3.5,
    setupFee: 0,
    installationFee: 0,
    deliveryFee: 0,
    routerFee: 0,
    activationFee: 35,
    voucherValue: 150,
    rewardCardValue: 0,
    cashbackValue: 0,
    billCreditValue: 0,
    freeMonthsDiscountValue: 0,
    otherUpfrontCosts: 0,
    otherDiscounts: 0,
    lastCheckedDate: '2026-06-01',
  },
  {
    dealId: 'SW-SKY-500',
    postcodeArea: 'SW',
    provider: 'Sky',
    packageName: 'Full Fibre 500 Sample',
    source: 'Provider Direct',
    speedMbps: 500,
    speedTier: '500-900 Mbps',
    advertisedMonthlyPrice: 38,
    contractLengthMonths: 24,
    annualAprilPriceRise: 3,
    setupFee: 0,
    installationFee: 0,
    deliveryFee: 0,
    routerFee: 0,
    activationFee: 0,
    voucherValue: 0,
    rewardCardValue: 75,
    cashbackValue: 0,
    billCreditValue: 0,
    freeMonthsDiscountValue: 0,
    otherUpfrontCosts: 0,
    otherDiscounts: 0,
    lastCheckedDate: '2026-06-01',
  },
  {
    dealId: 'SW-BT-150',
    postcodeArea: 'SW',
    provider: 'BT',
    packageName: 'Full Fibre 100 Sample',
    source: 'Comparison Site Sample',
    speedMbps: 150,
    speedTier: '100-300 Mbps',
    advertisedMonthlyPrice: 30.99,
    contractLengthMonths: 24,
    annualAprilPriceRise: 3,
    setupFee: 0,
    installationFee: 0,
    deliveryFee: 4.99,
    routerFee: 0,
    activationFee: 0,
    voucherValue: 50,
    rewardCardValue: 0,
    cashbackValue: 0,
    billCreditValue: 0,
    freeMonthsDiscountValue: 0,
    otherUpfrontCosts: 0,
    otherDiscounts: 0,
    lastCheckedDate: '2026-06-01',
  },
];

module.exports = sampleDeals;
